#!/usr/bin/bash

# Exit if any command fails
set -eux pipefail

# use my aws profile
export AWS_PROFILE=personal

# install dependencies into lib folder
pip install -t lib -r requirements.txt

# create a zip file with all dependencies and app files
pushd lib
zip ../lambda_function.zip -r .
popd
zip lambda_function.zip -u $(ls *.py)

# upload to S3
aws s3 cp lambda_function.zip s3://fast-api-app

# update lambda code
aws lambda update-function-code  \
  --function-name FastApiApp \
  --s3-bucket fast-api-app \
  --s3-key lambda_function.zip

## update lambda handler
#aws lambda update-function-configuration \
#  --function-name FastApiApp \
#  --handler main.aws_lambda_handler

# remove unnecessary files locally after deployment
rm -rf lib lambda_function.zip

